REPLACE INTO "capacity_factor_tech" VALUES('region','charge','a','generator',1.0,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('region','charge','b','generator',1.0,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('region','charge','c','generator',0.2,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('region','charge','d','generator',0.2,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('region','discharge','a','generator',0.1,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('region','discharge','b','generator',0.1,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('region','discharge','c','generator',0.01,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('region','discharge','d','generator',0.01,NULL);
REPLACE INTO "capacity_to_activity" VALUES('region', 'generator', 8760.0, NULL, 'MWh/MWy');
REPLACE INTO "capacity_to_activity" VALUES('region', 'dly_stor', 8760.0, NULL, 'MWh/MWy');
REPLACE INTO "capacity_to_activity" VALUES('region', 'seas_stor', 8760.0, NULL, 'MWh/MWy');
REPLACE INTO "capacity_to_activity" VALUES('region', 'demand', 8760.0, NULL, 'MWh/MWy');
REPLACE INTO "commodity" VALUES('ethos', 's', NULL, NULL);
REPLACE INTO "commodity" VALUES('electricity', 'p', NULL, NULL);
REPLACE INTO "commodity" VALUES('demand', 'd', NULL, NULL);
REPLACE INTO "commodity_type" VALUES('p','physical commodity');
REPLACE INTO "commodity_type" VALUES('a','annual commodity');
REPLACE INTO "commodity_type" VALUES('e','emissions commodity');
REPLACE INTO "commodity_type" VALUES('d','demand commodity');
REPLACE INTO "commodity_type" VALUES('s','source commodity');
REPLACE INTO "commodity_type" VALUES('w','waste commodity');
REPLACE INTO "commodity_type" VALUES('wa','waste annual commodity');
REPLACE INTO "commodity_type" VALUES('wp','waste physical commodity');
REPLACE INTO "cost_invest" VALUES('region','generator',2000,1000.0,'',NULL);
REPLACE INTO "cost_invest" VALUES('region','dly_stor',2000,1.0,'',NULL);
REPLACE INTO "cost_invest" VALUES('region','seas_stor',2000,100.0,'',NULL);
REPLACE INTO "cost_invest" VALUES('region','demand',2000,1.0,'',NULL);
REPLACE INTO "cost_variable" VALUES('region',2000,'generator',2000,1.0,NULL,NULL);
REPLACE INTO "cost_variable" VALUES('region',2000,'demand',2000,1.0,NULL,NULL);
REPLACE INTO "demand" VALUES('region',2000,'demand',8760.0,'MWh',NULL);
REPLACE INTO "demand_specific_distribution" VALUES('region',2000,'charge','a','demand',0.0,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('region',2000,'charge','b','demand',0.05,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('region',2000,'charge','c','demand',0.05,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('region',2000,'charge','d','demand',0.1,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('region',2000,'discharge','a','demand',0.0,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('region',2000,'discharge','b','demand',0.2,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('region',2000,'discharge','c','demand',0.2,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('region',2000,'discharge','d','demand',0.4,NULL);
REPLACE INTO "efficiency" VALUES('region', 'ethos', 'generator', 2000, 'electricity', 1.0, NULL, NULL);
REPLACE INTO "efficiency" VALUES('region', 'electricity', 'dly_stor', 2000, 'electricity', 1.0, NULL, NULL);
REPLACE INTO "efficiency" VALUES('region', 'electricity', 'seas_stor', 2000, 'electricity', 1.0, NULL, NULL);
REPLACE INTO "efficiency" VALUES('region', 'electricity', 'demand', 2000, 'demand', 1.0, NULL, NULL);
REPLACE INTO "limit_storage_level_fraction" VALUES('region','winter','b','seas_stor','e',0.5,NULL);
REPLACE INTO "limit_storage_level_fraction" VALUES('region','charge','b','dly_stor','e',0.5,NULL);
REPLACE INTO "metadata" VALUES('DB_MAJOR',4,'');
REPLACE INTO "metadata" VALUES('DB_MINOR',0,'');
REPLACE INTO "metadata_real" VALUES('global_discount_rate',0.05,'Discount Rate for future costs');
REPLACE INTO "metadata_real" VALUES('default_loan_rate',0.05,'Default Loan Rate if not specified in loan_rate table');
REPLACE INTO "operator" VALUES('e','equal to');
REPLACE INTO "operator" VALUES('le','less than or equal to');
REPLACE INTO "operator" VALUES('ge','greater than or equal to');
REPLACE INTO "region" VALUES('region',NULL);
REPLACE INTO "sector_label" VALUES('electricity',NULL);
REPLACE INTO "storage_duration" VALUES('region','dly_stor',4.0,NULL);
REPLACE INTO "storage_duration" VALUES('region','seas_stor',8760.0,NULL);
REPLACE INTO "technology" VALUES('generator','p','electricity',NULL,NULL,0,0,0,0,0,0,0,0,NULL);
REPLACE INTO "technology" VALUES('dly_stor','ps','electricity',NULL,NULL,0,0,0,0,0,0,0,0,NULL);
REPLACE INTO "technology" VALUES('seas_stor','ps','electricity',NULL,NULL,0,0,0,0,0,0,0,1,NULL);
REPLACE INTO "technology" VALUES('demand','p','electricity',NULL,NULL,0,0,0,0,0,0,0,0,NULL);
REPLACE INTO "technology_type" VALUES('p','production technology');
REPLACE INTO "technology_type" VALUES('pb','baseload production technology');
REPLACE INTO "technology_type" VALUES('ps','storage production technology');
REPLACE INTO "time_of_day" VALUES(0,'a',6,NULL);
REPLACE INTO "time_of_day" VALUES(1,'b',6,NULL);
REPLACE INTO "time_of_day" VALUES(2,'c',6,NULL);
REPLACE INTO "time_of_day" VALUES(3,'d',6,NULL);
REPLACE INTO "time_period" VALUES(0,2000,'f');
REPLACE INTO "time_period" VALUES(1,2005,'f');
REPLACE INTO "time_period_type" VALUES('e','existing vintages');
REPLACE INTO "time_period_type" VALUES('f','future');
REPLACE INTO "time_season" VALUES(0,'charge',0.5,NULL);
REPLACE INTO "time_season" VALUES(1,'discharge',0.5,NULL);
REPLACE INTO "time_season_sequential" VALUES(1,'summer','charge',0.417808,NULL);
REPLACE INTO "time_season_sequential" VALUES(2,'sept_w1','discharge',0.019178,NULL);
REPLACE INTO "time_season_sequential" VALUES(3,'sept_w2','charge',0.019178,NULL);
REPLACE INTO "time_season_sequential" VALUES(4,'sept_w3','discharge',0.019178,NULL);
REPLACE INTO "time_season_sequential" VALUES(5,'sept_w4','charge',0.019178,NULL);
REPLACE INTO "time_season_sequential" VALUES(6,'sept_29th','discharge',0.002740,NULL);
REPLACE INTO "time_season_sequential" VALUES(7,'sept_30th','charge',0.002740,NULL);
REPLACE INTO "time_season_sequential" VALUES(8,'winter','discharge',0.417808,NULL);
REPLACE INTO "time_season_sequential" VALUES(9,'apr_w1','charge',0.019178,NULL);
REPLACE INTO "time_season_sequential" VALUES(10,'apr_w2','discharge',0.019178,NULL);
REPLACE INTO "time_season_sequential" VALUES(11,'apr_w3','charge',0.019178,NULL);
REPLACE INTO "time_season_sequential" VALUES(12,'apr_w4','discharge',0.019178,NULL);
REPLACE INTO "time_season_sequential" VALUES(13,'apr_29th','charge',0.002740,NULL);
REPLACE INTO "time_season_sequential" VALUES(14,'apr_30th','discharge',0.002740,NULL);
