#
import os
import sys
from pathlib import Path
from typing import Any, cast

import tomlkit

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute

# this first import is to provide path the temoa package, which is referenced throughout
# and must be included separately from path the source files so that it is properly recognized
sys.path.insert(0, os.path.abspath('../../'))
# this addition provided direct abbreviated link to the modules in the model
sys.path.insert(1, os.path.abspath('../../temoa/temoa_model'))

# Import version from source (after sys.path setup)
from temoa.__about__ import __version__

# -- Project information from pyproject.toml ---------------------------------

# Read metadata from pyproject.toml
pyproject_path = Path(__file__).parent.parent.parent / 'pyproject.toml'
with open(pyproject_path) as f:
    pyproject_data = tomlkit.load(f)

project_metadata = cast('dict[str, Any]', pyproject_data['project'])
project = 'Tools for Energy Model Optimization and Analysis (Temoa)'
author = ', '.join(
    author['name'] for author in cast('list[dict[str, Any]]', project_metadata.get('authors', []))
)


# The short version
version = __version__.rsplit('.', 1)[0]
# The full version
release = __version__


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.githubpages',
    'sphinxcontrib.bibtex',
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'myst_parser',  # Enable Markdown support
    'sphinxcontrib.mermaid',  # Enable Mermaid diagrams
    'sphinx.ext.imgconverter',  # Support SVG to PDF conversion for LaTeX
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

bibtex_bibfiles = ['References.bib']

# The suffix(es) of source filenames.
# Support both reStructuredText and Markdown
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# Suppress warnings for duplicate labels and objects (intentional due to file inclusion and autodoc)
suppress_warnings = [
    'ref.duplicate',  # Duplicate labels between included RST files
    'autosummary',  # Autodoc duplicate object descriptions
    'ref.footnote',  # Unreferenced footnotes
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['default/static']


html_theme = 'sphinx_book_theme'
html_theme_options = {
    'repository_url': 'https://github.com/TemoaProject/temoa',
    'use_repository_button': True,
    'use_issues_button': True,
    'use_edit_page_button': True,
    'path_to_docs': 'docs/source',
    'show_navbar_depth': 2,
}
latex_logo = 'assets/logo_bottom_text.pdf'
html_logo = 'assets/logo_bottom_text.svg'

myst_enable_extensions = ['amsmath', 'colon_fence', 'dollarmath', 'html_image']
myst_fence_as_directive = ['mermaid']

mermaid_d3_zoom = True
mermaid_fullscreen = True
mermaid_include_elk = True
mermaid_include_mindmap = True

# -- Options for LaTeX output ------------------------------------------------
latex_engine = 'xelatex'
